apps/detector/models.py
from datetime import datetime

from apps.app import db

class UserImage(db.Model):
  __tablename__ = 'user_image'
  id = db.Column(db.Integer, primary_key=True)
  user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
  image_path = db.Column(db.String(255))
  is_detected = db.Column(db.Boolean, default=False)
  created_at = db.Column(db.DateTime, default=datetime.now)
  updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)

class UserImageTag(db.Model):
  __tablename__ = 'user_image_tags'
  id = db.Column(db.Integer, primary_key=True)
  user_image_id = db.Column(db.Integer, db.ForeignKey('user_image.id'))
  tag_name = db.Column(db.String(255))
  created_at = db.Column(db.DateTime, default=datetime.now)
  updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)
  

apps/detector/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField, FileRequired
from wtforms import SubmitField

class UploadImageForm(FlaskForm):
  image = FileField(
    validators=[
      FileRequired('업로드할 이미지를 선택하세요'),
      FileAllowed(["jpg", "jpeg", "png"], "지원되지 않는 확장자입니다.")
    ]
  )
  submit = SubmitField("업로드")

apps/detector/__init__.py
import apps.detector.models

apps/detector/views.py
from flask import Blueprint, render_template, current_app, send_from_directory, redirect, url_for, flash
from flask_login import login_required, current_user
import uuid
from pathlib import Path
import random
import cv2
import torch
import torchvision
from PIL import Image
import numpy as np
import torchvision.transforms.functional
from flask_wtf.csrf import generate_csrf

from apps.detector.forms import UploadImageForm
from apps.app import db
from apps.detector.models import UserImage, UserImageTag
from apps.crud.models import User

dt = Blueprint(
  "detector",
  __name__,
  template_folder="templates"
)

@dt.route('/')
def index():
  images = (
    db.session.query(User, UserImage)
              .join(UserImage)
              .filter(User.id == UserImage.user_id)
              .all()
  )

  csrf_token = generate_csrf()

  user_image_tag_dict = {}

  for image in images:
    user_image_tags = (
      db.session.query(UserImageTag)
        .filter(UserImageTag.user_image_id == image.UserImage.id)
        .all()
    )
    user_image_tag_dict[image.UserImage.id] = user_image_tags

  return render_template('detector/index.html', images = images, user_image_tag_dict=user_image_tag_dict, csrf_token=csrf_token)

@dt.route('/images/<path:filename>')
def image_file(filename):
  return send_from_directory(current_app.config['UPLOAD_FOLDER'], filename)

@dt.route('/upload', methods=["GET", "POST"])
@login_required
def upload_image():
  form = UploadImageForm()

  if form.validate_on_submit():
    # 전송받은 파일을 저장
    file = form.image.data
    
    # 이미지 파일의 확장자 추출
    ext = Path(file.filename).suffix
    uuid_file_name = str( uuid.uuid4() ) + ext

    # 이미지를 저장
    image_path = Path(current_app.config['UPLOAD_FOLDER'], uuid_file_name)
    file.save(image_path)

    # DB에 저장
    user_image = UserImage(user_id=current_user.id, image_path=uuid_file_name)
    db.session.add(user_image)
    db.session.commit()
    
    # 저장이 끝나면 index페이지로 이동
    return redirect(url_for('detector.index'))

  return render_template('detector/upload.html', form=form)


# 랜덤 색상 리턴
def make_color(labels):
  colors = [[random.randint(0,255) for _ in range(3)] for _ in labels]
  color = random.choice(colors)
  return color

# 선 두께 생성
def make_line(result_image):
  line = round(max(result_image.shape[0:2]) * 0.002) + 1
  return line

# 이미지에 선을 그려주는 함수
def draw_lines(c1, c2, result_image, line, color):
  cv2.rectangle(result_image, c1, c2, color, thickness=line)
  return cv2


def draw_texts(result_image, line, c1, cv2, color, labels, label):
  display_text = f'{labels[label]}'
  font = max(line - 1, 1)
  t_size = cv2.getTextSize(display_text, 0, fontScale=line / 3, thickness=font)[0]
  c2 = c1[0] + t_size[0], c1[1] - t_size[1] - 3
  cv2.rectangle(result_image, c1, c2, color, -1)
  cv2.putText(
    result_image, display_text, (c1[0], c1[1] - 2),
    0, line / 3, [255, 255, 255], thickness=font, lineType=cv2.LINE_AA
  )

  return cv2

def exec_detect(target_image_path):
  labels = current_app.config['LABELS']
  image = Image.open(target_image_path)

  image_tensor = torchvision.transforms.functional.to_tensor(image)
  model = torch.load(Path(current_app.root_path, 'detector', 'model.pt'))

  model = model.eval()

  output = model([image_tensor])[0]
  tags = []
  result_image = np.array(image.copy())

  for box, label, score in zip(output['boxes'], output['labels'], output['scores']):
    if score > 0.5 and labels[label] not in tags:
      color = make_color(labels)
      line = make_line(result_image)
      c1 = ( int(box[0]), int(box[1]) )
      c2 = ( int(box[2]), int(box[3]) )
      cv2 = draw_lines(c1, c2, result_image, line, color)
      cv2 = draw_texts(result_image, line, c1, cv2, color, labels, label)
      tags.append(labels[label])

  if tags:
    detected_image = str(uuid.uuid4()) + '.jpg'

    detected_image_path = str( 
      Path(current_app.config['UPLOAD_FOLDER'], detected_image)
    )

    cv2.imwrite(detected_image_path, cv2.cvtColor(result_image, cv2.COLOR_RGB2BGR))
    return tags, detected_image
  else:
    return tags, None
  
def save_detected_image_tags(user_image, tags, detected_image):
  user_image.image_path = detected_image
  user_image.is_detected = True
  db.session.add(user_image)

  for tag in tags:
    user_image_tag = UserImageTag(user_image_id=user_image.id, tag_name=tag)
    db.session.add(user_image_tag)
  
  db.session.commit()

@dt.route('/detect/<string:image_id>', methods=["POST"])
@login_required
def detect(image_id):
  user_image = db.session.query(UserImage).filter(UserImage.id == image_id).first()

  if user_image is None:
    flash('해당 이미지가 존재하지 않습니다.')
    return redirect(url_for('detector.index'))

  target_image_path = Path(current_app.config['UPLOAD_FOLDER'], user_image.image_path)
  tags, detected_image = exec_detect(target_image_path)

  if not tags:
    flash('감지된 물체가 없습니다.')
    return redirect(url_for('detector.index'))
  
  try:
    save_detected_image_tags(user_image, tags, detected_image)
  except Exception as e:
    flash('물체 감지 결과 저장 중 오류가 발생')
    db.session.rollback()

  return redirect(url_for('detector.index'))

apps/detector/templates/detector/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>물체감지</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">　
    <div class="container">
        <a class="navbar-brand " href="{{ url_for('detector.index') }}">detector</a>
        
        <ul class="navbar-nav">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <span class="nav-link">{{ current_user.username }}</span>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('auth.logout') }}" class="nav-link">로그아웃</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.signup') }}">회원가입</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
            </li>
            {% endif %}
        </ul>
    </div>
  </nav>
  
  <section class="conatiner">
    {% block content %}
    {% endblock %}
  </section>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

apps/detector/templates/detector/index.html
{% extends "detector/base.html" %}

{% block content %}
  <h1>Detector Index Page</h1>
  <div class="col-md-10 text-right dt-image-register-btn">
    <a href="{{ url_for('detector.upload_image') }}" class="btn btn-primary">이미지 등록</a>
  </div>

  {% for img in images %}
  <div class="card col-md-7 dt-image-content">
    <header class="d-flex justify-content-between">
      <div class="dt-image-username">{{ img.User.username }}</div>
    </header>
    <section>
      <img src="{{ url_for('detector.image_file', filename=img.UserImage.image_path) }}" alt="">
    </section>
  </div>
  {% endfor %}

{% endblock %}

apps/detector/templates/detector/upload.html
{% extends "detector/base.html" %}

{% block content %}
<div>
  <h3>이미지 등록 페이지</h3>
  <p>업로드할 이미지를 선택하세요</p>
  <form action="{{ url_for('detector.upload_image') }}" method="post" enctype="multipart/form-data" novalidate>
    {{ form.csrf_token }}
    <div>
      {{ form.image(class='form-control-file') }}
    </div>
    <div>
      {% for error in form.image.errors %}
        <span style="color: red;">{{ error }}</span>
      {% endfor %}
    </div>
    <hr>
    <div>
      {{ form.submit(class='btn btn-primary') }}
    </div>
  </form>
</div>
{% endblock %}